# Regresión lineal en Python


## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [35]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [36]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [37]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [38]:
x = data[feature_cols]
y = data["Sales"]

In [39]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1)
selector = selector.fit(x,y)

C:\Users\51931\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [26]:
selector.support_

array([ True,  True, False])

In [27]:
selector.ranking_

array([1, 1, 2])

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
X_pred = X[["TV", "Radio"]]

In [44]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [42]:
lm.intercept_


2.9210999124051362

In [43]:
lm.coef_

array([0.04575482, 0.18799423])

In [45]:
lm.score(X_pred, Y)

0.8971942610828956