# El método de k-means

In [1]:
import numpy as np

In [3]:
data = np.random.random(90).reshape(30,3)
data

array([[0.75575448, 0.09581125, 0.41311493],
       [0.98680326, 0.24590227, 0.92009828],
       [0.46803574, 0.87571669, 0.3672087 ],
       [0.90053285, 0.50004004, 0.67004431],
       [0.21922872, 0.26305994, 0.8853354 ],
       [0.20387917, 0.32200667, 0.19812861],
       [0.36558317, 0.6715646 , 0.0884703 ],
       [0.97426419, 0.14919292, 0.48062767],
       [0.43798288, 0.11292277, 0.49659342],
       [0.98923055, 0.5679534 , 0.4068418 ],
       [0.66189253, 0.21308882, 0.20409361],
       [0.93093739, 0.49748242, 0.50621924],
       [0.3776976 , 0.24542826, 0.14518824],
       [0.24609549, 0.52781112, 0.10955048],
       [0.61953406, 0.46180503, 0.26147323],
       [0.29197971, 0.16151925, 0.48418209],
       [0.5837021 , 0.47534018, 0.74065036],
       [0.31238544, 0.93254607, 0.90957525],
       [0.65291122, 0.40115032, 0.30736695],
       [0.62346215, 0.2064206 , 0.55820913],
       [0.97431096, 0.86931158, 0.12110019],
       [0.23149074, 0.37800874, 0.73977599],
       [0.

In [7]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.93093739, 0.49748242, 0.50621924],
       [0.65291122, 0.40115032, 0.30736695]])

In [8]:
from scipy.cluster.vq import vq

In [9]:
vq(data, clust_centers)

(array([1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 0, 1, 0]),
 array([0.3391037 , 0.48755453, 0.51280915, 0.16664222, 0.73566093,
        0.46885661, 0.45121729, 0.35190584, 0.40629542, 0.13505602,
        0.21473978, 0.        , 0.35537843, 0.46975883, 0.0830618 ,
        0.46792969, 0.41954806, 0.85707816, 0.        , 0.31891803,
        0.53707995, 0.60424195, 0.61562476, 0.77879919, 0.75074706,
        0.37072826, 0.56237647, 0.51746026, 0.74882725, 0.34621271]))

In [10]:
from scipy.cluster.vq import kmeans

In [11]:
kmeans(data, clust_centers)

(array([[0.83460612, 0.49045892, 0.65086561],
        [0.38269862, 0.36333866, 0.43754046]]), 0.38121682378727)